// Code generated by protoc-gen-defaults. DO NOT EDIT.

package topicv1beta1

import (
	"context"
	"github.com/bxcodec/faker"
)

// MockTopicAPIServer is the mock implementation of the TopicAPIServer. Use this to create mock services that
// return random data. Useful in UI Testing.
type MockTopicAPIServer struct{}

// Create is mock implementation of the method Create
func (MockTopicAPIServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	var res CreateResponse
	if err := faker.FakeData(&res); err != nil {
		return nil, err
	}
	return &res, nil
}
