// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package postgresql

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	packr.PackJSONBytes("./migrations", "1.sql", "\"LS0gK21pZ3JhdGUgVXAKQ1JFQVRFIFRBQkxFIElGIE5PVCBFWElTVFMgZXZlbnRzICgKICAiaWQiIHNlcmlhbCBwcmltYXJ5IGtleSBub3QgbnVsbCwKICAicmVhbG1faWQiIHRleHQgTk9UIE5VTEwsCiAgImV2ZW50X2lkIiB0ZXh0IE5PVCBOVUxMLAogICJ0eXBlIiB0ZXh0IE5PVCBOVUxMLAogICJib2R5IiBieXRlYSBOT1QgTlVMTCwKICAiaW5zZXJ0ZWRfYXQiIHRpbWVzdGFtcCg2KSBOT1QgTlVMTCBERUZBVUxUIHN0YXRlbWVudF90aW1lc3RhbXAoKQopOwoKLS0gK21pZ3JhdGUgRG93bgpEUk9QIFRBQkxFIGV2ZW50czs=\"")
}
